Python 3.10.1 (v3.10.1:2cd268a3a9, Dec  6 2021, 14:28:59) [Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.

============================================================ RESTART: /Users/kunalsharma/Desktop/python assignment 1/pythonASSIGNMENT1.py ============================================================
Entre first number= 6
Entre second number= 8
Entre third number= 4
Average=  6.0
***************************************************************
Entre Gross Income= 80000
Entre Number of Dependents= 1
Taxable income=  67000.0
Tax=  13400.0
***************************************************************
Entre your SID= 21104096
Entre your Name= KUNAL SHARMA
Entre F for Female, M for Male , U for Unknown= M
Entre your Course Name= INTRODUCTION TO COMPUTING
Entre your CGPA= 9.5
[21104096, 'KUNAL SHARMA', 'M', 'INTRODUCTION TO COMPUTING', 9.5]
***************************************************************
Entre Marks of 1st Student= 8
Entre Marks of 2nd Student= 5
Entre Marks of 3rd Student= 6
Entre Marks of 4th Student= 10
Entre Marks of 5th Student= 3
[3, 5, 6, 8, 10]
***************************************************************
New List after deleting fourth item=  ['RED', 'GREEN', 'WHITE', 'PINK', 'YELLOW']
New List after replacing BLACK And PINK=  ['RED', 'GREEN', 'WHITE', 'PURPLE']
